version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://easygas:password@db:5432/easygas
      - VITE_SOLANA_RPC_URL=${VITE_SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}
      - NODE_ENV=production
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=easygas
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=easygas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
